name: PR Review Secret Caller
on:
  workflow_run:
    workflows: ["PR Review Listener"]
    types: [completed]

jobs:
  call-api:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check access to the secret
        env:
          API_KEY: ${{ secrets.TEST_SECRET }}
        run: |
          set -euo pipefail
          if [ -z "$API_KEY" ]; then
            echo "❌ ERROR: Required secret API_KEY is not set."
            echo "   Please go to Settings → Secrets and set the secret for this repository."
            exit 1
          else
            echo "✅ Secret API_KEY is set."
          fi
