name: Test Workflow B - Check Secret Access

on:
  workflow_run:
    workflows: ["Test Workflow A - Store PR Data"]
    types:
      - completed

jobs:
  check-secret-access:
    name: Check PAT Secret Access
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      pull-requests: read
      actions: read
      checks: write

    steps:
      - name: Check if PAT secret is available
        env:
          PAT_TOKEN: ${{ secrets.TEST_SECRET }}
        run: |
          echo "=== Secret Access Check ==="
          if [ -z "$PAT_TOKEN" ]; then
            echo "❌ TEST_SECRET is NOT available"
            echo "Secret is empty or not set"
            exit 1
          else
            echo "✅ TEST_SECRET is AVAILABLE"
            echo "Secret length: ${#PAT_TOKEN} characters"
            echo "First 4 characters: ${PAT_TOKEN:0:4}****"
          fi
          echo ""

      - name: Summary
        run: |
          echo "=== Test Summary ==="
          echo "✓ Workflow B executed successfully via workflow_run trigger"
          echo "✓ Secrets are accessible in this workflow"
          echo ""
          echo "🎉 This approach WORKS for CODEOWNERS check!"
