name: Test Workflow A - Store PR Data

on:
  pull_request_review:
    types: [submitted, edited, dismissed]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to test with'
        required: true
        type: number

jobs:
  store-pr-data:
    name: Store PR Review Data
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Exit early for non-approved reviews
        if: github.event.review.state != 'approved'
        run: |
          echo "Skipping - review is not an approval (state: ${{ github.event.review.state }})"
          exit 0
