name: Test Workflow B - Check Secret Access

on:
  workflow_run:
    workflows: ["Test Workflow A - Store PR Data"]
    types:
      - completed

jobs:
  check-secret-access:
    name: Check PAT Secret Access
    runs-on: ubuntu-latest
    # Only run if Workflow A succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      pull-requests: read
      actions: read
      checks: write

    steps:
      - name: Display workflow run info
        run: |
          echo "=== Workflow Run Info ==="
          echo "Triggered by workflow: ${{ github.event.workflow_run.name }}"
          echo "Workflow run ID: ${{ github.event.workflow_run.id }}"
          echo "Conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Current branch: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}"
          echo ""

      - name: Download PR context artifact
        uses: actions/download-artifact@v4
        with:
          name: pr-context
          path: pr-context/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Read PR context
        id: pr-context
        run: |
          echo "=== PR Context Data ==="
          cat pr-context/data.json
          echo ""

          # Extract values and set as outputs
          PR_NUMBER=$(jq -r '.pr_number' pr-context/data.json)
          REVIEWER=$(jq -r '.reviewer' pr-context/data.json)
          PR_TITLE=$(jq -r '.pr_title' pr-context/data.json)

          echo "PR Number: $PR_NUMBER"
          echo "Reviewer: $REVIEWER"
          echo "PR Title: $PR_TITLE"
          echo ""

          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo "reviewer=$REVIEWER" >> $GITHUB_OUTPUT

      - name: Check if PAT secret is available
        env:
          PAT_TOKEN: ${{ secrets.TEST_SECRET }}
        run: |
          echo "=== Secret Access Check ==="
          if [ -z "$PAT_TOKEN" ]; then
            echo "❌ TEST_SECRET is NOT available"
            echo "Secret is empty or not set"
            exit 1
          else
            echo "✅ TEST_SECRET is AVAILABLE"
            echo "Secret length: ${#PAT_TOKEN} characters"
            echo "First 4 characters: ${PAT_TOKEN:0:4}****"
          fi
          echo ""

      - name: Summary
        run: |
          echo "=== Test Summary ==="
          echo "✓ Workflow B executed successfully via workflow_run trigger"
          echo "✓ Running on base branch context: ${{ github.ref }}"
          echo "✓ Successfully downloaded artifacts from Workflow A"
          echo "✓ PR Context: #${{ steps.pr-context.outputs.pr_number }} by ${{ steps.pr-context.outputs.reviewer }}"
          echo "✓ Secrets are accessible in this workflow"
          echo ""
          echo "🎉 This approach WORKS for CODEOWNERS check!"
