name: Test Workflow A - Store PR Data

on:
  pull_request_review:
    types: [submitted, edited, dismissed]

jobs:
  store-pr-data:
    name: Store PR Review Data
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Exit early for non-approved reviews
        if: github.event.review.state != 'approved'
        run: |
          echo "Skipping - review is not an approval (state: ${{ github.event.review.state }})"
          exit 0

      - name: Store PR context data
        run: |
          echo "Storing PR review data for Workflow B..."

          mkdir -p pr-context

          cat > pr-context/data.json << 'EOF'
          {
            "pr_number": ${{ github.event.pull_request.number }},
            "reviewer": "${{ github.event.review.user.login }}",
            "review_state": "${{ github.event.review.state }}",
            "pr_title": "${{ github.event.pull_request.title }}",
            "pr_author": "${{ github.event.pull_request.user.login }}",
            "base_ref": "${{ github.event.pull_request.base.ref }}",
            "head_ref": "${{ github.event.pull_request.head.ref }}",
            "repository": "${{ github.repository }}"
          }
          EOF

          echo "Stored data:"
          cat pr-context/data.json

      - name: Upload PR context
        uses: actions/upload-artifact@v4
        with:
          name: pr-context
          path: pr-context/
          retention-days: 1
