name: Workflow B — Check Secret on Main (reusable)

on:
  workflow_call:
    inputs:
      pr_number:
        required: true
        type: number

jobs:
  check-on-main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write

    steps:
      - name: Checkout main head
        uses: actions/checkout@v4
        with:
          ref: refs/heads/main
          fetch-depth: 0

      - name: Verify TEST_SECRET is set
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        run: |
          if [ -z "$TEST_SECRET" ]; then
            echo "❌ TEST_SECRET is NOT set."
            exit 1
          else
            echo "✅ TEST_SECRET is present."
          fi
