name: On PR Review → Trigger Workflow B

on:
  pull_request_review:
    types: [submitted, edited, dismissed]

permissions:
  contents: read

jobs:
  call-b:
    runs-on: ubuntu-latest
    steps:
      - name: Call reusable workflow B
        uses: ./.github/workflows/workflow-b.yml
        with:
          pr_number: ${{ github.event.pull_request.number }}
